import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import { Geist, Geist_Mono } from "next/font/google";
import SideBar from "@/components/SideBar";
import "./globals.css";
import "./leaflet.css";
import { NextIntlClientProvider } from "next-intl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <PrimeReactProvider>         
            <div className="flex">
            <SideBar />
              <main className="flex-1 lg:ml-0 w-full">{children}</main>
            </div></PrimeReactProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
